### ISSUE TITLE
ridge glmnet 코드 수정 (예 3.2)

### ISSUE THREAD

**Issue by youngroklee-ml** [youngroklee-ml/data-mining-techniques#22]
- [ ] 교재와 glmnet 사이의 lambda 값 변환식 확인
- [ ] glmnet lambda값 수정

**Comment by youngroklee-ml** [comment]
`{penalized}` 패키지 사용
- 목적함수는 (maximization 기준) loglikelihood - `lambda1` * L1-norm - (1/2) * `lambda2` * L2-norm
- 교재와 비교하여 lambda1은 1/2로, lambda2는 그대로 입력해야 함
- loglikelihood는 함수 `loglik()`로 확인 가능
- penalty term은 함수 `penalty()`로 확인 가능

**Comment by hyeleev33** [comment]
아래 내용 확인해줘서 감사해요.

이제 좀 명확하네요.


이혜선

________________________________
보낸 사람: Youngrok Lee ***@***.***>
보낸 날짜: 2024년 2월 25일 일요일 오후 6:21
받는 사람: youngroklee-ml/data-mining-techniques
참조: hyeleev33; Assign
제목: Re: [youngroklee-ml/data-mining-techniques] ridge glmnet 코드 수정 (예 3.2) (Issue #22)


{penalized} 패키지 사용

  *   목적함수는 (maximization 기준) loglikelihood - lambda1 * L1-norm - (1/2) * lambda2 * L2-norm
  *   교재와 비교하여 lambda1은 1/2로, lambda2는 그대로 입력해야 함
  *   loglikelihood는 함수 loglik()로 확인 가능
  *   penalty term은 함수 penalty()로 확인 가능
