### ISSUE TITLE
ch11 코드 수정

### ISSUE THREAD

**Issue by youngroklee-ml** [youngroklee-ml/data-mining-techniques#25]
- [x] 예 11.1 - 다른 거리 척도 추가 (혹은 예 11.2 코드 작성)
- [x] 예 11.3 - 예제에 나타난 수치를 직접적으로 보이도록 코드 수정

**Comment by hyeleev33** [comment]
감사합니다. 반영하여 11장 R코드 삽입하도록 할께요.

**Comment by hyeleev33** [comment]
감사합니다. 반영하여 11장 R코드 삽입하도록 할께요.

 

이혜선
