### ISSUE TITLE
예 12.4 군집 수 결정 - R 코드와 교재 내용 차이

### ISSUE THREAD

**Issue by youngroklee-ml** [youngroklee-ml/data-mining-techniques#4]
@hyeleev33 예 12.4 군집 수 결정
R 코드 - total within sum of square, gap statistics, average silhouette width
교재 - RMS 표준편차, R2, SPR

확인 부탁드립니다.

**Comment by hyeleev33** [comment]
전치혁교수님께 확인해보니, SAS에서 제공하는 결과기준으로 편집해서 RMS 표준편차, R2, SPR를 넣은것이라고 합니다.

교재 내용을 gap statistics, average silhouette width으로 기술해도 좋다고 하시는데, 교재 내용까지 바꿀 여력이 안되서 일단 그대로 둔겁니다. 이영록 박사가 판단할때 중요척도로 사용된다고 생각하는 척도 1-2가지로 교재를 바꾸어도 됩니다.

**Comment by youngroklee-ml** [comment]
@hyeleev33 네, 우선 교재 본문에 설명된 방법들은 그대로 두고, average silhouette width 설명 추가하고, 예제는 average silhouette width 으로 변경하면 어떨까 합니다. 13장에서 silhouette을 사용하여 군집 수를 결정하는 예제들이 있기 때문에, 12장에서 해당 방법을 설명하고 가는 것이 좋겠습니다.

현재 교재 본문에 설명된 방법들 중 일부/전체를 제외할 것인지는 추후 논의할 수 있는 부분일 것 같습니다. 연습문제 12.6과도 연관된 부분입니다.
