### ISSUE TITLE
13장 - R 코드와 교재 내용 차이

### ISSUE THREAD

**Issue by youngroklee-ml** [youngroklee-ml/data-mining-techniques#5]
@hyeleev33 교재와 R 코드가 일치하지 않는 부분들이 있습니다. 아래 사항 확인 부탁드립니다.

- [x] **예 13.1** 군집 결정 silhoutte만 포함하고 나머지 제거?
- [x] **예 13.3** 교재에서는 다른 데이터 사용. 교재와 R 코드 데이터 일치 필요?
- [x] **예 13.3** 실루엣 결과가 교재에는 없는 부분 - R 코드에서 제외?
- [x] **예 13.8** 군집 결과가 교재와 다름. 교재에는 4번 객체가 노이즈로 분류. R 코드에서는 4번 객체가 2번 군집으로 분류. 교재 수정 필요?
- [x] **예 13.8** 실루엣 결과가 교재에는 없는 부분 - R 코드에서 제외?

**Comment by hyeleev33** [comment]
예13.1 -> Rcode에서 실루엣만 남기고 제거함
예 13.3 PAM의 예제에서 교재에서는 일부데이터(6개)를 사용했는데 (아마도 계산을 쉽게 하기 위한것인듯..) R코드는 그대로 두도록 할께요. 전치혁교수님께 교재 PAM의 예제에서 10개 데이터를 그대로 사용하는게 어떨지 문의할께요. DBSCAN에서도 10개 데이터(동일)하게 사용함.
예13.8 DBSCAN R code에서 eps=2.5로 수정했어요. 

=> 수정한 ch13_cluster.dbscan.R 과 hwp파일을 이메일로 보냅니다.

**Comment by hyeleev33** [comment]
예 13.3 실루엣 결과가 교재에는 없는 부분 - R 코드에서 제외?
=> PAM에서는 k-means와 dbscan에서 사용한 10개의 데이터 중에서 6개만 뽑아서 교재에서 설명하고 있는데, 전치혁교수님이 6개 데이터 예제를 그대로 사용하신다고 하면 '[그림 13.3] PAM 결과와 시각화도표'는 추후 삭제하도록 하지요. 

 '[그림 13.3] PAM 결과와 시각화도표' 는 10개 데이터를 모두 사용한 결과입니다.

**Comment by hyeleev33** [comment]
'[그림 13.3] PAM 결과와 시각화도표' - ch13 교재에서 삭제 (전치혁교수님이 설명을 위해 6개 데이터를 사용하여 PAM계산과정을 보인거라고 합니다.)

이메일로 ch13 교재.hwp보냄 (그림 numbering수정함)

**Comment by youngroklee-ml** [comment]
@hyeleev33 빠르게 검토해주셔서 감사드립니다. 수정해주신 부분 조만간 반영하여 업데이트하도록 하겠습니다.

**Comment by youngroklee-ml** [comment]
@hyeleev33 위 사항 모두 반영하였습니다. 아래 사항을 추가 수정하였습니다. 검토 부탁드립니다.

- PAM의 경우, R 코드를 교재와 일치하는 데이터 *data/ch13_pam.csv*를 만들어, 해당 데이터에 대한 수행 결과를 첨부하였습니다.
- 시각화의 경우, `stand = FALSE` 인자를 추가하여, x축과 y축이 원 데이터 scale로 표현되도록 하였습니다.
- 각 예제(kmeans, PAM, DBSCAN)를 각각 하나의 R 코드로 구성하는 것이 어떨까 하여, *revised* 폴더에 *ch13_kmeans.R*, *ch13_pam.R*, *ch13_dbscan.R*로 각각 저장해 보았습니다. R 코드 구성에 대해 다음 회의에서 논의하면 좋을 것 같습니다.

**Comment by hyeleev33** [comment]
이영록 박사

 

아래 내용 모두 확인했습니다. 

R코드 정리 매우 좋네요 (kmeans, pam, dbscan 세개 파일로 분리한것도 좋습니다)
stand = FALSE, plot is much better!!

ch13.hwp에 PAM의 ouput그림 첨부하여 이메일로 첨부합니다.

감사합니다. 

 

이혜선
